### ISSUE TITLE
Skal id-elementet under decision_ref ha lik notasjon som andre id-elementer?

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#103]
@steinarnoem: I nåværende informasjonsmodell står det i avsnitt 4.4.4 at decision_ref skal ha et id-element med notasjonen ref_id i stedet for bare id når man ser på de underliggende detaljene i JSON formatet. Er det bare en trykkleif, for det er vel ingen god grunn til at den skal være ulik id-elementet som vi har på de fleste andre attributtene? Samtidig ser jeg at det samme går igjen i kapittel 7 Vedlegg B, mens jeg nok hadde lagt inn lik notasjon som for andre attributter i grunnlaget for tabellen i avsnitt 6.2.1 Attributter koblet mot HL7 FHIR AuditEvent. Jeg mistenker jo at enkelte utviklere fort vil snuble i denne forskjellen (altså overse den), siden det er en såpass subtil forskjell på kun et av attributtene, og at det derfor er lurere at dette er konsistent med slik det er for alle andre attributter.

**Comment by steinarnoem** [comment]
Jeg endret alle instanser til å bruke "id".
https://github.com/NorskHelsenett/Tillitsrammeverk/commit/983b93ff6c30534c4b1f3ce65acf845c3b4bd0b5
