### ISSUE TITLE
Ta inn ISO 14265 som gyldig kodeverk for purpose_of_use?

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#104]
Det som benyttes i XUA/SAML-billetten for løsningen som er i drift for pasientens journaldokumenter er koder fra ISO 14265. De aktuelle kodene i det kodeverket som nå er i bruk bør antakelig også være gyldige koder for å sikre mest mulig fleksibilitet i overgangsperioden fra gammelt kodeverk skal utfases til nytt kodeverk er innført?

Jeg legger spesielt merke til at koden for saksbehandler (Health service management and quality assurance) som er angitt på utviklerportalen, [Spesifikasjon for SAML for XDS dokumentdeling
Felt purposeofUse](https://utviklerportal.nhn.no/informasjonstjenester/pasientens-journaldokumenter-i-kjernejournal/loesningsbeskrivelser/saml-token/) ikke nødvendigvis mapper helt med noen av de gyldige kodene som nå er foreslått fra HL7-kodeverket PurposeOfUse, men jeg mistenker at det er dette koden COC (coordination of care) er tenkt brukt til? Kan det være at koden HOPERAT (healthcare operations) med den underliggende koden HDM (healthcare delivery management) er like aktuell for å beskrive saksbehandling og derfor også burde være gyldig? Eventuelt har ikke HL7-kodeverket fullgod dekning av det som i dag dekkes i ISO 14265. Jeg mangler tilgang til ISO-kodeverkene for å se det komplette kodeverket her, men det har kanskje NHN tilgang til?

**Comment by steinarnoem** [comment]
Gode innspill Richard. Jeg har tenkt på TREAT som default-PoU for dokumentdeling, og hadde sett for meg at de underliggende kodene kunne benyttes når det var behov for ekstra oppmerksomhet/oppfølging eller spesielle tilgangsregler.

Du ser samme hierarki definert for definisjonen av ActReason https://terminology.hl7.org/5.2.0/CodeSystem-v3-ActReason.html.

**Comment by steinarnoem** [comment]
Dersom vi skal akseptere TREAT, ETREAT, COC og BTG bør vi også beskrive regler for hvordan de ulike kodene skal håndteres hos NHN og hos dokumentkilden. Skal f.eks. bruk av ETREAT og BTG føre til spesiell oppfølging hos både dokumentkilde og de andre involverte i verdikjeden?

**Comment by steinarnoem** [comment]
Her er et innspill fra Kristin Rønneberg hos NHN, som beskriver hvordan PoU-kodene tolkes av KJ:

<table>
<tr>
<th>Kjernejournal portal</th><th>Betydning I kjernejournal</th><th>Purpose of use (HL7)</th>
</tr>
<tr>
<td>Samtykke</td><td>Pasienten har gitt sitt samtykke til at jeg kan gis tilgang til hans/hennes kjernejournal</td><td> TREAT</td></tr>
<tr><td rowspan="5">Unntak fra samtykke</td>Helsepersonell i den akuttmedisinske kjede</td><td>TREAT</td></tr>
<tr><td>Pasientens fastlege</td><td>TREAT</td></tr>
<tr><td>Lege eller sykepleier i spesialisthelsetjenesten</td><td>TREAT</td><td></tr>
<tr><td>Helsepersonell med legemiddelansvar i sykehjem eller hjemmesykepleien </td><td>TREAT</td></tr>
<tr><td>Helsepersonell med legemiddelansvar i spesialisthelsetjenesten</td><td>TREAT</td></tr>
<tr><td rowspan="3">Akuttsituasjon</td><td>Alvorlig fare for pasientens liv</td><td>ETREAT, BTG eller ERTREAT</td></tr>
<tr><td>Ikke tid til å innhente samtykke fra pasienten</td><td>ETREAT, BTG eller ERTREAT</td></tr>
<tr><td>Pasienten er ikke i stand til å gi samtykke pga sin fysiske eller psykiske tilstand</td><td>ETREAT, BTG eller ERTREAT</td></tr>
</table>

Hvis det er gitt samtykke – eller man ikke trenger samtykke – blir koden TREAT

Hvis det er en akuttsituasjon er spørsmålet om man skal gi en "generell" kode (ETREAT), eller detaljere med BTG/ERTREAT

Ingen av disse kodene overstyrer blokkering, bare sperring.

**Comment by steinarnoem** [comment]
@micer2004  - har NHN tilgang til ISO 14265?
Kan vi sjekke opp om HL7 dekker kodene som KJ bruker fra ISO

**Comment by steinarnoem** [comment]
Beslutning: vi definerer at ISO kodeverket også er et gyldig kodeverk.
