### ISSUE TITLE
Bruk av "authority" og "assigner" for å angi autoritativ kilde eller forvaltningsansvar

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#105]
Jeg har fått en kommentar på at det er litt vanskelig å forstå forskjellen på "authority" og "assigner".. Burde vi konsolidert? Eller kan vi gi en tydeligere forklaring på når man bruker hvilket attributt..

**Comment by mortsten** [comment]
I DIPS har man, etter hva jeg kan huske brukt assigner på alle attributtene. Forskjellen bør beskrives om man beholder 2.

**Comment by steinarnoem** [comment]
"assigner" for id
"authority" som noen forvalter
