### ISSUE TITLE
Forretningsregler knyttet til attributtet "legal_entity"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#110]

**Comment by richardhus** [comment]
Attributtet skal inneholde helsepersonellets virksomhetstilhørighet. Det er den registrerte enheten i Brønnøysundregisteret som helsepersonellet formelt yter helsehjelp for som skal oppgis, ikke vikarbyrå eller tilsvarende virksomhet som kan være personellets primære arbeidsgiver.

Informasjonen dokumenterer hvilken virksomhet som er ansvarlig for personellets tilgang, og vil benyttes som et av flere elementer fra attesten som i sum dokumenterer grunnlaget for at tilgang blir gitt av kilder, og dermed inngå i pasientjournalens innsynslogg hos kildene. Denne opplysningen vil benyttes ved lovpålagt etterfølgende kontroll av tilgangene hos kilder, samt eventuelt vises i løsningen for digitalt innbyggerinnsyn i tilgangslogg fra kilder dersom dette elementet på generelt grunnlag vurderes å gjøre tilgangene mer forståelige for innbyggere.
