### ISSUE TITLE
Forretningsregler knyttet til attributtet "point_of_care"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#111]

**Comment by richardhus** [comment]
Attributtet skal inneholde helsepersonellets arbeidssted, som også kan omtales som behandlingsstedet helsepersonellet formelt er tilknyttet. Det er den registrerte underenheten i Brønnøysundregisteret som helsepersonellet formelt utfører sitt arbeide ved som skal oppgis.

Det er et generelt krav til alle norske virksomheter at aktivitet skal kunne rapporteres per geografisk sted og per registrert næringskode i Brønnøysund som det drives virksomhet ved, og derfor skal det være registrert slike underenheter i Brønnøysundregisteret for de fleste virksomheter i Norge.

For virksomheter som eventuelt ikke har registrert noen underliggende enheter i Brønnøysundregistrene skal den overordnede enheten oppgis i dette attributtet.

Informasjonen vil i første rekke benyttes som et av flere elementer fra attesten som i sum dokumenterer grunnlaget for at tilgang blir gitt, og dermed inngå i pasientjournalens innsynslogg. Denne opplysningen vil benyttes ved lovpålagt etterfølgende kontroll av tilgangene, samt eventuelt vises i løsningen for digitalt innbyggerinnsyn i tilgangslogg dersom dette elementet på generelt grunnlag vurderes å gjøre tilgangene mer forståelige for innbyggere.
