### ISSUE TITLE
Forretningsregler knyttet til attributtet "healthcare_service"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#113]

**Comment by richardhus** [comment]
Attributtet "healthcare-service" (helsehjelpstjeneste) angir hvilken type helsetjenester som leveres/ytes til pasienten ved virksomheten der helsepersonellet jobber. Helsehjelpstjenesten som dokumenteres er grunnlaget for at helsepersonellet trenger tilgang til pasientens helseopplysninger. Et alternativt begrep enn helsehjelpstjeneste, som beskriver det tilsvarende grunnlaget i spesialisthelsetjenesten, er fagområde.

Det er ikke alltid slik at helsehjelpstjeneste eller fagområde er registrert og knyttet til tilganger som helsepersonellet har til pasienten, for eksempel:
- Når pasienten ikke er i et planlagt forløp hos virksomheten, men behandles eksternt
- Dersom pasienten ønsker dialog i etterkant av et avsluttet forløp
- Det har oppstått en akuttsituasjon som krever rask tilgang til pasienten

For spesialisthelsetjenesten er tanken at manglende verdi i "healthcare-service" vil kunne forklares av verdien som formidles i "purpose-of-use-details".

Det er flere kodeverk som er aktuelle for å beskrive helsehjelpstjeneste, de fleste er koblet til tjenestebasert adressering, se detaljert beskrivelse under attributtet i [informasjonsmodellen.](https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md#441-healthcare-service-helsetjenestetype).

Informasjonen vil i første rekke benyttes som et av flere elementer fra attesten som i sum dokumenterer grunnlaget for at tilgang blir gitt, og dermed inngå i pasientjournalens innsynslogg hos kilden. Denne opplysningen vil benyttes ved lovpålagt etterfølgende kontroll av tilgangene på kildesiden, samt eventuelt vises i løsningen for digitalt innbyggerinnsyn i tilgangslogg fra kilder, dersom dette elementet på generelt grunnlag vurderes å gjøre tilgangene mer forståelige for innbyggere.

Ved flere mulige valg bør det vektlegges hva som i størst mulig grad kan bidra til å avklare hva som er bakgrunnen for tilgangen. Som hovedregel bør det være så presist som mulig heller enn et mer overordnet nivå, men likevel et nivå pasienten og eksternt helsepersonell med størst sannsynlighet har et forhold til.
