### ISSUE TITLE
Forretningsregler knyttet til attributtet "purpose_of_use_details"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#115]

**Comment by richardhus** [comment]
Dette attributtet er ment for å formidle hvilken spesifikk hendelse aller aktivitet, som er registrert i helsepersonellets egen virksomhet, og som er bakgrunnen for at helsepersonellet søker tilgang til pasientens helseopplysninger. Det kan være at en pasient trenger å få vurdert en henvisning, er planlagt å møte til en konsultasjon, er under behandling i en poliklinisk konsultasjon eller er innlagt, skal følges opp av helsepersonellet eller liknende. Det kan også være at pasienten, pasientens pårørende/verge eller pasientens eksterne behandler har tatt kontakt med helsepersonellet eller en annen planlagt eller uplanlagt .
