### ISSUE TITLE
Forretningsregler knyttet til attributtet "decision_ref"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#116]

**Comment by richardhus** [comment]
Attributtet er en referanse til den lokale tilgangsbeslutningen hos konsumenten. Med tilgangsbeslutning menes det som er dokumentert hos en konsument i forbindelse med at et helsepersonell har fått tilgang:

- Etter pålogging i lokalt EPJ må helsepersonellet kunne navigere seg frem til de aktuelle pasientene de skal yte helsehjelp til. Dette fordrer tilgang til en oversikt over pasienter som de potensielt skal behandle. Oversikten kan være intern eller hentes fra andre virksomheter. Da er det referanse til denne tilgangsbeslutningen som skal oppgis
- Ved valg av en spesifikk pasient, som helsepersonellet trenger tilgang til mer detaljert informasjon om enn det som fremkommer i oversikten, må det foreligge en referanse til den mer spesifikke tilgangsbeslutningen for tilgang til denne pasienten

Tilgangsbeslutningen er utgangspunktet for videre tilgang til andre virksomheter og nasjonale løsninger. Det er den mest spesifikke tilgangsbeslutningen som til enhver tid skal identifiseres.

Formålet med dette attributtet er at alle parter i en kjede av involverte virksomheter og systemer, skal kunne gjenfinne logginnslag som har opphav fra den opprinnelige tilgangsbeslutningen hos konsument.

Attributtet skal formidle informasjon om helsepersonellet har tatt seg selv tilgang (selvautorisasjon), eller om det er en automatisert (systemavledet) tilgangsbeslutning. Det er også tilrettelagt for at en mer utdypende systemavledet beskrivelse kan formidles for å sikre best mulig forståelse av grunnlaget for tilgangen.
