### ISSUE TITLE
Forretningsregler knyttet til attributtet patient: "point_of_care"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#118]

**Comment by richardhus** [comment]
Attributtet skal inneholde pasientens behandlingssted så fremt behandlingen foregår i helsepersonellets egen virksomhet, og det er registrert en kontakt med en organisasjonsenhet i helsepersonellets egen virksomhet som er grunnlaget for tilgangen. Det er den registrerte underenheten i Brønnøysundregisteret som pasientens kontakt tilhører som skal oppgis.

Det er et generelt krav til alle norske virksomheter at aktivitet skal kunne rapporteres per geografisk sted og per registrert næringskode i Brønnøysund som det drives virksomhet ved, og derfor skal det være registrert slike underenheter i Brønnøysundregisteret for de fleste virksomheter i Norge.

For virksomheter som eventuelt ikke har registrert noen underliggende enheter i Brønnøysundregistrene skal den overordnede enheten oppgis i dette attributtet så lenge kriteriene for at dette attributtet skal brukes er oppfylt.

Dersom pasienten behandles ved en annen virksomhet enn helsepersonellets, for eksempel ved behov for tilgang for å kunne bistå en kollega i en annen virksomhet som har pasienten til behandling hos seg, eller dersom pasienten selv eller pårørende har henvendt seg uten at dette er knyttet til en registrert kontakt med helsepersonellets virksomhet, skal ikke dette attributtet benyttes. Det er altså kun når pasienten har en registrert kontakt i helsepersonellets egen virksomhet, og helsehjelp knyttet til denne kontakten er grunnlaget for at helsepersonellet trenger tilgang til helseopplysningene for pasienten, at dette attributtet skal formidle den offisielle underenheten pasienten har sin registrerte kontakt ved. Informasjonen skal formidles uavhengig av om helsepersonellet trenger tilgangen som følge av helsehjelp de selv yter direkte til pasienten, eller indirekte som følge av at de trenger tilgangen for å bistå kolleger i egen virksomhet.

Informasjonen vil i første rekke benyttes som et av flere elementer fra attesten som i sum dokumenterer grunnlaget for at tilgang blir gitt, og dermed inngå i pasientjournalens innsynslogg. Denne opplysningen vil benyttes ved lovpålagt etterfølgende kontroll av tilgangene, samt eventuelt vises i løsningen for digitalt innbyggerinnsyn i tilgangslogg dersom dette elementet på generelt grunnlag vurderes å gjøre tilgangene mer forståelige for innbyggere.
