### ISSUE TITLE
Pasientens identifikator må knyttes til attesten

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#120]
En attest representerer helsepersonellets grunnlag for tilgang til en  spesifikk pasient (eller potensielt flere), og skal kunne gjenbrukes ved kall til forskjellige tjenester mens helsepersonellet har pasienten til behandling.

Attesten skal entydig knyttes til pasienten som er inne til behandling, slik at den ikke kan brukes for tilgang til andre pasienter.

**Comment by richardhus** [comment]
En attest skal også kunne benyttes uten binding til en spesifikk pasient, men dette gjelder kun i tilfeller der pasienten ikke er kjent og for tilgang til et langt smalere sett av opplysninger om de spesifikke pasientene. For eksempel ved henting av en oversikt over pasienter som er innkommende til en legevakt i ambulanser, eller oversikt over pasienter som er innlagt ved en gitt enhet. Så snart man har en spesifikk pasient som man trenger tilgang til å se mer detaljert informasjon om vil kravet være at attesten er knyttet til denne pasienten.

**Comment by steinarnoem** [comment]
Duplikat
