### ISSUE TITLE
Bør patient være et array?

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#123]
Ved administrasjon av helsehjelp kan det være naturlig at den som planlegger eller administrer jobber med flere pasienter til samme tid.
I slike tilfeller vil attesten kunne være lik for alle pasienter, bortsett fra pasient_id.

Jeg vil gjerne diskutere om det er fornuftig å omdefinere pasientinformasjonen i spesifikasjonen slik at den tar høyde for flere pasienter.

Forslag:

patients: [
      "patient": {
	      "id": "05076600324",
	      "name": "Kognar Maman",
	      "system": "urn:oid:2.16.578.1.12.4.1.4.1",
	      "authority": "https://www.skatteetaten.no"
      },
      "patient": {
	            "id": "06087700435",
	            "name": "Agnar Kognan",
	            "system": "urn:oid:2.16.578.1.12.4.1.4.1",
	            "authority": "https://www.skatteetaten.no"
            }
]

Noen tanker @richardhus, @eirikbroen, @mortsten ?

**Comment by eirikbroen** [comment]
:) liker egentlig tanken her, men kanskje noe sent i løpet å innføre? Det jeg liker godt med forslaget er at det som du skriver @steinarnoem kan være tilfeller hvor attest gjelder for flere pasienter, men også at vi da kan sette attributt `patients` som påkrevd og type til array og samtidig tillatte tomt array. På den måten så støtter vi brukstilfeller hvor pasient ikke er kjent for eksempel for tilgang til system som oversikt over innkommende ambulanser.

**Comment by richardhus** [comment]
Jeg støtter @eirikbroen her fullt ut, har ingen umiddelbare motforestillinger mot å gjøre dette om til et array, ut over at det kan bli interessant hvordan vi eventuelt får parset et slikt array i de ulike komponentene som eventuelt trenger det på sikt.
