### ISSUE TITLE
Endre navngiving av "patient_id" til "identifier"

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#124]
Personling mening: jeg liker strukturer bedre enn sammensatte strenger..  

Kan vi i navngi attributtene for pasienten på følgende måte?
```
patient : {
  "identifier": {
    "id": "05076600324",
    "name": "Kognar Maman",
    "system": "urn:oid:2.16.578.1.12.4.1.4.1",
    "authority": "https://www.skatteetaten.no"
  },
  8<..>8
}
```

Noen tanker @mortsten, @eirikbroen, @richardhus ?

**Comment by eirikbroen** [comment]
Jeg støtter i utgangspunktet denne, er tilhenger av lik struktur. Det jeg er mer usikker på er om vi da egentlig burde ta en gjennomgang av navngivning generelt. Er vel da naturlig at f.eks practitioner også følger samme mønster 

`practitioner : {
  "identifier": {
    "id": "05076600324",
    "name": "Dr Pille",
    "system": "urn:oid:2.16.578.1.12.4.1.4.1",
    "authority": "https://www.skatteetaten.no"
  },
 "hpr": {
    "id": "",
    "system": "urn:oid:2.16.578.1.12.4.1.4.4",
    "authority": "https://www.helsedirektoratet.no/"
  },
  "authorization": {
	  "code": "LE",
	  "text": "Lege",
	  "system": "urn:oid:2.16.578.1.12.4.1.1.9060",
	  "assigner": "https://www.helsedirektoratet.no/"
  }
  8<..>8
}`

men vi har også flere attributter som jeg tror det er vanskelig å splitte opp f.eks `practitioner : legal_entity` og `practitioner : point_of_care`
