### ISSUE TITLE
Korrigering av figuren for Informasjonsmodell

### ISSUE THREAD

**Issue by OK-SverreM** [NorskHelsenett/Tillitsrammeverk#140]
I figuren for Informasjonsmodell (kapittel 4.1.4) er det tatt med to attributter som **ikke** er del av rammeverket / spesifikasjonen:
- Formell rolle/stilling helsepersonellet opptrer i kraft av på vegne av organisasjonen
- Funksjon helsepersonellet har og opptrer i kraft av på vegne av organisasjonen

Disse bør fjernes umiddelbart. Jeg registrerer at de allerede skaper noe forvirring hos de som leser på disse sidene.

**Comment by steinarnoem** [comment]
Der var det noe gammel moro ja..  jeg fjerner asap
