### ISSUE TITLE
"hpr-nr" - blanding av "kodeverk-attributt" og "identitet-attributt"

### ISSUE THREAD

**Issue by troelde** [NorskHelsenett/Tillitsrammeverk#145]
Ref. [4.3.5 "hpr-nr": Helsepersonellnummer](https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md#435-hpr-nr-helsepersonellnummer)

HPR-nr er vel en identifikator? I beskrivelsen er "code" og "assigner" brukt.

**Comment by steinarnoem** [comment]
https://github.com/NorskHelsenett/Tillitsrammeverk/commit/a7f66adb547666ef3a03932cf419fdcd7c7b860c
