### ISSUE TITLE
OID for norske organisasjonsnummer

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#19]
OID for organisasjonsnummer er 2.16.578.1.12.4.1.4.101 - ref: https://www.ehelse.no/teknisk-dokumentasjon/oid-identifikatorserier-i-helse-og-omsorgstjenesten

**Comment by eirikbroen** [comment]
Jepp. Feil i eksempelet i dokumentasjonen på denne siden https://helseid.atlassian.net/wiki/spaces/HELSEID/pages/5636230/Passing+organization+identifier+from+a+client+application+to+HelseID

**Comment by steinarnoem** [comment]
Har oppdatert spesifikasjonene på github samt dokumentet på HelseID sine dokumentasjonssider
