### ISSUE TITLE
Angående "Sikkerhetsutfordringer med logging: Log4J som eksempel"

### ISSUE THREAD

**Issue by troelde** [NorskHelsenett/Tillitsrammeverk#2]
Hei @steinarnoem!

Forbehold om at jeg forstår dette riktig. Dette er jo innsynslogging (auditlogging), mens Log4J brukes jo til systemlogging, altså en annen type logging. 

Det jobbes med en nasjonal implementasjonsguide for FHIR AuditEvent som viser hvordan token-attributtene (claims) skal mappes fra token til AuditEvent, se https://github.com/HL7Norway/AuditEvent.  

Denne bør selvsagt tilpasses nasjonal informasjonsmodell for tillitsrammeverket

Hilsen
Trond :-)

**Comment by steinarnoem** [comment]
Hei @troelde, veldig godt å se at du er med :)

Risikoen jeg ønsker å synliggjøre er at det er vanskelig/umulig å ha kontroll over alle programvarekomponenter som er i bruk. Log4J problematikken er i mitt syn først og fremt et eksempel på at man ikke kan vite hvilke sårbarheter man åpner for, og at man bør designe med tanke på å redusere risiko. 

For øvrig tror jeg at Log4J (og lignende programvarebibliotek) både brukes i forbindelse med forskjellige logger, også audit events.

Ellers er det også greit å vite [at man ikke kan stole blindt på WAF for å stoppe angrep..](https://claroty.com/team82/research/js-on-security-off-abusing-json-based-sql-to-bypass-waf)

**Comment by troelde** [comment]
Ja, jeg er med :-)  Jeg er skeptisk til bruk av denne typen bibliotek for auditlogging, men er enig i at man som prinsipp ikke kan ha kontroll på hvilke programvarebibliotek som er i bruk. Poenget mitt var bare å si at det er langt strengere krav til hvordan en audit-/innsynslogg lagres og oppbevaring enn en standard dump av en tekstbasert loggfil (*.log). Den må være transaksjonssikker og beskyttet mot endring.  Det samme kravet til integritet som man eller vil forvente av lagring av payload i meldingen.

**Comment by steinarnoem** [comment]
Synes du at den siste versjonen av teksten klinger bedre @troelde?
