### ISSUE TITLE
Krav om at "User-Agent" i http header settes til en verdi som gir mening for native klienter ved kall til HelseID

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#32]

**Comment by dag-at-udelt** [comment]
Denne er gammel og ganske god, fokuset er (selvfølgelig) apper på mobile enheter - men ser ingen grunn til at det ikke kan være et utgangspunkt for windowsapplikasjoner med integrert nettleser.

https://www.scientiamobile.com/correctly-form-user-agents-for-mobile-apps/

**Comment by steinarnoem** [comment]
Stoff til implementasjonsguide (alle http requests)

**Comment by steinarnoem** [comment]
Har praktisk verdi for API eiere hvis det inneholder informasjon om hvilket EPJ/fagsystem som utfører http-request.. 
Det er en fin anledning å innføre dette i forbindelse med PJD, for å unngå å innføre endringer senere..

NHN tar dette med seg internt i arbeidet hos de ulike tjenestene (f.eks. HelseID og API)..
