### ISSUE TITLE
Norm for informasjonssikkerhet

### ISSUE THREAD

**Issue by troelde** [NorskHelsenett/Tillitsrammeverk#44]
Bør ikke Norm for informasjonssikkerhet også refereres  i tillegg lovverket?

Norm for informasjonssikkerhet er jo styrende for de som kobler seg til Norsk Helsenett.

**Comment by steinarnoem** [comment]
commit: [123a455
](https://github.com/NorskHelsenett/Tillitsrammeverk/commit/123a45546a5995fa78c21f149f8e0a25f4dcca3e)
