### ISSUE TITLE
Tilgangskontroll gjelder også retten til å motsette seg tilgjengeliggjøring (sperring/reservasjon)

### ISSUE THREAD

**Issue by troelde** [NorskHelsenett/Tillitsrammeverk#45]
Mener det bør fram at tilgangskontroll ikke kun er knyttet til tjenstlig behov, men også kontroll av pasientens reservasjoner knyttet til utlevering av pasientopplysninger (sperring) som en del av å "støtte opp under innbyggers rettigheter".

**Comment by steinarnoem** [comment]
Det ser ut til at informasjonsmodellen tar for seg flere forskjellige formål i dag.
Lukker derfor dette issuet..
