### ISSUE TITLE
Datamodell - Spørsmål om attributter

### ISSUE THREAD

**Issue by eirikbroen** [NorskHelsenett/Tillitsrammeverk#5]
Har et par spørsmål til attributter i utkast til datamodell

_structural_role_ Antar at de fleste EPJ systemer ikke har en mapping fra brukerrolle til de tre foreslåtte verdiene. Denne attributten er satt opp som obligatorisk. Er tanken her at denne verdien angir hvilken rolle personell har i i en gitt behandlingsrelasjon og som ikke kan utledes fra HPR informasjon eller mangel på denne?

_functional_role_ Foreslått kodeverk her er satt til å være STYRK-08 og at informasjonskilde er EPJ/HR system. Antar at mange virksomheter har EPJ uten direkte integrasjon med HR system og dermed enten må lage en slik integrasjon eller gjøre en form for dobbeltføring. Burde vi foreslå en mulig mapping fra funksjonelle roller i EPJ. Typ - EPJ Rolle "Lege" i et system i primærhelsetjenesten = STYRK-08 2211 - Allmennpraktiserende Leger?

_locality_ Bør ta en diskusjon på hva som er forventining knyttet til verdi på dette attributtet. Kan se for meg flere situasjoner hvor det for eksempel ikke er fornuftig å spesifisere avdeling - Eks. Overgrepsmottak. Hva er formålet med denne attributten? Er det hovedsaklig å gjøre det enklere for pasient å forstå innsynslogg?

_purpose_of_use_ Dette attributtet diskuterte vi endel i pilot Oslo Kommune/HSØ, kom der frem til at det i legevaktsammenheng var lite verdifullt å avgi noen annen verdi enn "Behandling". Ser [EHDSI](http://docs.oasis-open.org/security/xspa/v1.0/saml-xspa-1.0-cs01.html#_Toc234556166) spesifikasjon lister ganske få mulige verdier. Naturlig nivå å legge seg på? Dette er nok også en verdi som ikke finnes direkte i EPJ og som vi bør tilby eksempel på mapping av hvis den skal være obligatorisk.

**Comment by steinarnoem** [comment]
Hei Eirik, du stiller veldig gode spørsmål!

Jeg har et forslag til prosess og tilnærming her - kan vi opprette ett diskusjonstema pr attributt i diskusjonsforumet? Jeg tror det blir lettere å behandle innspillene og eventuelle diskusjoner hvis temaene er adskilte.

S

**Comment by eirikbroen** [comment]
Hei Steinar,

Enig, det er et godt forslag til prosess. Ser nå at Helge startet en diskusjonstråd på funksjonell rolle i går. Jeg legger inn innholdet i denne saken i relevante tråder under diskusjon så fortsetter vi der.
