### ISSUE TITLE
Nytt kapittel med egen ordliste med begrepsdefinisjoner?

### ISSUE THREAD

**Issue by troelde** [NorskHelsenett/Tillitsrammeverk#50]
F.eks. beskrive hva som menes med begrepet _sikkerhetsbillett_. Ta med alternative navn f.eks. sikkerhetsbevis., og eksempler kan være SAML eller JWT.  Referere til autoritative kilder f.eks. RFCer etc med offisielle definisjoner.

**Comment by steinarnoem** [comment]
Ref: 91162e8c070d6d36320f64ac7c4b7dd3da79c512
