### ISSUE TITLE
Bør "purpose_of_use_details" være et offisielt norsk kodeverk

### ISSUE THREAD

**Issue by arnedh** [NorskHelsenett/Tillitsrammeverk#64]
Hei, 
tar meg den frihet å melde inn et par ting om https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md.

1: feilstavingen practictioner bør byttes ut, i eksempler og dataformater

2:  under healthcare_service nevnes kodeverk som er utgått.
8627 Tjenestetyper innen spesialisthelsetjenesten - erstattet med 8655
Linkene til kodeverkene er feil. 
(Generelt bør disse kodeverkene samsvare med dem som brukes av RESH, HPR og andre registre hos https://register-web.test.nhn.no/docs/api/ - RESH lister 8653, 8654, 8655 (og iblant 8652, 8663))

3: Bør ikke kodeverket for "purpose_of_use_details" være et offisielt norsk kodeverk og dermed ligge i Volven og ikke være DIPS-proprietært? Også logisk at kodeverket 9151 for kommunene ligger under healthcare service?

**Comment by steinarnoem** [comment]
Til info: jeg opprettet punkt 1 & 2 som separate issues.

Svar til punkt 3:
Når kodene for "purpose of use details" blir tatt I bruk vil de etter hvert kunne bli en standard.
Det vi foreløpig ser er at detaljering av purpose of use vil være forskjellig avhengig av typen helsetjeneste virksomheten leverer. For eksempel ser det ut som om det er en forskjell mellom sykehus og kommunale helsetjenester.

HL7 norge jobber med standarder knyttet til FHIR og XDS, og det er kanskje naturlig at en eventuell standardisering går via dette arbeidet?

**Comment by mortsten** [comment]
Støttes
