### ISSUE TITLE
Bør care_relation:healthcare_service i informasjonsmodellen reflekteres på samme måte i SAML-sikkerhetsbeviset knyttet til IHE XDS?

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#65]
I informasjonsmodellen er attributter som ikke egentlig er spesifikke for verken helsepersonellet eller pasienten når disse sees uavhengig av hverandre lagt under care_relation. I SAML-sikkerhetbeviset vi i dag mottar fra nasjonal XCA ligger dette attributtet under subject, som altså tilsier at helsehjelpstjenesten er koblet mot helsepersonellet og egentlig uavhengig av hvilken pasient det er snakk om. Det kan godt være riktig i mange tilfeller, men strengt tatt burde vel healthcareservice heller ligge utenfor subject ettersom det vi er på jakt etter her er hvilken helsehjelpstjeneste som ytes av helsepersonellet for den aktuelle pasienten som sikkerhetsbeviset og forespørselen gjelder. Et og samme helsepersonell kan godt primært yte en spesifikk helsehjelpstjeneste i de fleste tilfeller, men når de inngår i en behandling av pasienter er det behandlingen pasienten mottar fra virksomheten som er relevant for å kunne forstå hvorfor dette helsepersonellet har et tjenstlig behov for tilgang de aktuelle helseopplysningene når det gjelder denne spesifikke pasienten i akkurat dette tilfellet. Mitt forslag er derfor at healtchares_service legges utenfor subject direkte på rot-nivå i SAML-sikkerhetsebeviset.

**Comment by steinarnoem** [comment]
Ekstern dokumentasjon skrives av dokumentdelingsteamet - krever litt koordinering..
