### ISSUE TITLE
Strukturen i foreslått informasjonsmodell

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#66]
Informasjonsmodellens care_relation-gruppering inneholder etter det jeg kan se nå enkelte attributter som egentlig er knyttet til helsepersonellet eller pasienten uavhengig av hverandre. Med det mener jeg for eksempel at legal_entity, point_of_care og department kan og bør legges både på helsepersonellet og på pasienten fremfor å ligge i care_relation som beskriver relasjonen mellom dem. Dette fordi helsepersonellet fint kan tilhøre et annet arbeidssted/behandlingssted enn pasienten i sin behandling av pasienten. Da er det ryddig og også mest intuitivt for leverandører å hente frem helsepersonellets tilhørighet og legge det i disse elementene under subject, mens de kan hente frem pasientens tilhørighet separat og legge det under patient. Har man det kun under care_relation, så får man ikke uttrykt både helsepersonellets og pasientens tilhørighet, man må velge en av disse og hvilken er det da riktigst å velge?

**Comment by richardhus** [comment]
Hvis det i hovedsak er pasientens behandlingssted og pasientens organisasjonstilhørighet vi formidler, hva gjør vi når det for eksempel er en eksplisitt beslutning om tilgang til pasienten med bakgrunn i en henvendelse fra pasientens behandler, pasienten selv eller pasientens pårørende? Skal man da ikke ha med noen organisasjonstilhørighet i det hele tatt ut over legal_entity? Pasienten har ingen organisasjonstilhørighet i dette tilfellet. Helsepersonellet har jo det, og det kunne blitt formidlet, men hvis vi gjør det må regelen bli at det primært er pasientens tilhørighet som formidles i disse elementene, alternativt helsepersonellets tilhørighet dersom vi ikke har noen tilhørighet på pasienten. Man da begynner dette å bli veldig lite forutsigbart for kildene og innbyggere som skal bruke disse dataene.

**Comment by richardhus** [comment]
Fra loggkontrollørene ved Oslo universitetssykehus HF har jeg fått følgende tilbakemelding om behovet for helsepersonellets organisasjonstilhørighet:
_Det er direkte alvorlig og i strid med hva OUS har satt som premisser for dette tidligere dersom man legger seg på et så mangelfullt detaljnivå for helsepersonellet som gjør oppslag.
 
Vi kan forstå at for mindre virksomheter kan det bli kompliserende, men:
a)	Oslo kommune og andre store by-kommuner er ikke små virksomheter (!)
b)	Det bør kunne gå an å ha disse feltene som «ikke påkrevd» for små virksomheter, slik at vi ikke blokkerer muligheten for systemer som er i stand til å levere dataene. Større virksomheter bør pålegges å levere disse.
 
Statistisk logganalyse gjør sammenligninger av helsepersonellets aktiviteter i systemet sett mot andres aktiviteter i samme virksomhet. Dette er en sentral del i loggkontroll-løsningen. Hvis vi kun får ansattdata på høyeste nivå, vil verdien av disse analysene bli svært lav eller null i større virksomheter, ettersom man da vil sammenlikne personer som utfører svært forskjellige oppgaver. Som et eksempel, si at vi undersøker oppslagene en lege på en legevakt i en gitt kommune gjør mot en pasient. Det er da viktig at vi kan sammenlikne denne legen med de øvrige kollegaene hans på legevakten. Gjør de andre legene som arbeider her også oppslag på denne pasienten? I en løsning der vi kun har øverste nivå vil denne legen bli sammenliknet med leger på sykehjem, helsehus osv., uten at vi vet hvor verken vedkommende eller de øvrige ansatte jobber.

Dette har også med å forsøke å danne seg et bilde av helsepersonellets fagområde vs. hvilke dokumenter det gjøres oppslag på. Vi som kilde vet hvilke dokumenter og hvilke avdelinger internt hos oss disse tilhører, men vi vet for lite om helsepersonellet hos konsument hvis dine forslag ikke tas til følge. 
 
Og det er også inkonsistent med tiltaket NHN har med å etablere (og vedlikeholde….) en liste over kontaktpersoner for loggoppfølging i de ulike foretakene (nasjonalt), et tiltak som jeg forstår er begrunnet i å redusere personvernulempen ved at forespørsler fra en virksomhet til en annen havner på toppnivå._

I tillegg har gjorde DIPS meg oppmerksom på at helsepersonellets organisasjonstilhørighet på tilstrekkelig detaljert nivå også er nødvendig for tilgangskontroll, ettersom Helse Sør-Øst sine regionale sikkerhetskrav til behandlingsrettede helseregister blant annet inneholder krav om å kunne sperre for alle unntatt personell fra en gitt organisasjonsenhet eller organisasjon eller sperre for alle fra en gitt organisasjonsenhet eller organisasjon. Så disse attributtene er ikke bare for loggformål, de er også relevante for tilgangskontroll.

**Comment by steinarnoem** [comment]
Oppsummert: tydeliggjør forskjellen mellom informasjon om pasient og helsepersonell

**Comment by steinarnoem** [comment]
Tidligere har vi snakket om at "legal entity" skal representere den dataansvarlige virksomheten, jeg går ut ifra at dette ikke endrer seg?

**Comment by steinarnoem** [comment]
commit: https://github.com/NorskHelsenett/Tillitsrammeverk/commit/41d71acaa000dfd8d1adeebaee0c6259e4079097
