### ISSUE TITLE
Bør navn formidles strukturert som fornavn og etternavn?

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#77]
I Helse Sør-Øst ser vi at for fagsystemer som skal opprette brukere/personer basert på innhold mottatt i sikkerhetsbevis, så har vi behov for at navn formidles strukturert, altså at fornavn og etternavn formidles i hvert sitt informasjonselement, fremfor å være sammenslått til et informasjonselement slik både HelseID og SAML-sikkerhetsbevisene for helsenorge.no og kjernejournal har det i dag. I tillegg ser jeg når jeg sammenlikner med HL7 FHIR at man for personnavn i stor grad legger opp til å bruke datatypen HumanName (http://hl7.org/fhir/datatypes.html#HumanName), der det er støtte for elementene given (fornavn), family (etternavn) og text (fullt navn) pluss et par andre metadatainformasjonselementer som enn så lenge neppe er aktuelle. For logging til FHIR AuditEvent vil det også være en fordel om vi har en mest mulig kompatibel struktur på navn når dette formidles i sikkerhetsbevis.

**Comment by runegri** [comment]
Foreslår å utrykke navn på samme måte som Persontjenesten. De skiller mellom fornavn, mellomnavn og etternavn, men i praksis er fornavn og mellomnavn slått sammen. 
Se her: https://utviklerportal.nhn.no/informasjonstjenester/persontjenesten/persontjenesten/persontjenesten/openapi/persontjenesten-api/ søk etter Name.

Vi ender da med følgende struktur:

```
	"practitioner": {
		"pid": {
			"id": "04056600324",
                        **"given_name": "Magnar",
                        "middle_name": "",
                        "family_name": "Koman",**
			"name": "Magnar Koman",
			"system": "urn:oid:2.16.578.1.12.4.1.4.1",
			"authority": "https://www.skatteetaten.no"
		},
                ...
```

**Comment by richardhus** [comment]
Høres veldig fint ut!

**Comment by mortsten** [comment]
Støttes
