### ISSUE TITLE
Tydeliggjøre gyldige verdier for attributtet Purpose of Use

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#81]
Gjøre det helt tydelig i dokumentasjonen at aktuelt verdisett er kun 3 verdier (fra det mer omfattende kodeverket [https://terminology.hl7.org/ValueSet-v3-PurposeOfUse.htmlhttps://terminology.hl7.org/ValueSet-v3-PurposeOfUse.html](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fterminology.hl7.org%2FValueSet-v3-PurposeOfUse.htmlhttps%3A%2Fterminology.hl7.org%2FValueSet-v3-PurposeOfUse.html&data=05%7C01%7CSteinar.Noem%40nhn.no%7C2c1304b62801481bf74308dbb4655f92%7Ce3dac4b39b0b4f4186239392d0d566dc%7C0%7C0%7C638302119725054249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bbZJQegOWmfmrBwwRRPsuqj5f33gu%2FDRC9LSr6brenA%3D&reserved=0)): TREAT/treatment, ETREAT/Emergency Treatment og COC/coordination of care.

**Comment by eirikbroen** [comment]
Bør vi også inkludere [BTG](https://terminology.hl7.org/CodeSystem-v3-ActReason.html#v3-ActReason-BTG) slik at liste med lovlige verdier blir TREAT/treatment, ETREAT/Emergency Treatment, COC/coordination og BTG/Break the glass

Sett med koder bør inn i et nasjonalt kodeverk slik at det kan refereres til med OID. Hvordan får vi inn et slikt kodeverk?

**Comment by steinarnoem** [comment]
Jeg har noen spørsmål knyttet til informasjonsmodellen dersom vi tillater BTG.
Min forståelse av BTG er at dette er en form for selvautorisasjon som overstyrer tilgangsstyringsregler. Er antagelsen at EPJ har den samme informasjon om helsepersonellets relasjon til pasienten som ved normal tilgangsstyring? Eller vil det kunne oppstå tilfeller hvor man ikke kjenner til autorisasjon, department, healthcare service osv?

**Comment by steinarnoem** [comment]
Commit: https://github.com/NorskHelsenett/Tillitsrammeverk/commit/7172c87e7b5744fe88a1fc51acb8440d0d33a6e8
