### ISSUE TITLE
Retningslinjer for bruk av attributtet Purpose of Use

### ISSUE THREAD

**Issue by steinarnoem** [NorskHelsenett/Tillitsrammeverk#82]
Lage tydelige retningslinjer for i hvilke scenarioer hver av disse er aktuelle å bruke, gjerne med et par-tre eksempler fra ulike helsetjenester.

**Comment by steinarnoem** [comment]
Er dette en del av første leveranse? Kan denne utsettes til neste versjon?

**Comment by eirikbroen** [comment]
***TREAT/treatment***
Skal benyttes når forespørsel om tilgang til helsedata skjer i direkte forbindelse med ytelse av helsehjelp som ikke er å regne som akutt. Tilgangsbeslutning hos konsument følger standard regler for tilgangsstyring. 

**Eksempler:** 
Planlagt legekonsultasjon hos spesialist
Behandling hos fastlege som ikke faller under øyeblikkelig hjelp
Oppfølging av behandlingsplan i virksomhet innen primærhelsetjenesten

***ETREAT/Emergency Treatment***
Skal benyttes når forespørsel om tilgang til helsedata skjer i direkte forbindelse med ytelse av helsehjelp innen akuttkjeden. Tilgangsbeslutning hos konsument følger standard regler for tilgangsstyring. 

**Eksempler:**
Behandling ved akuttmottak på sykehus eller legevakt
Behandling i ambulanse, via kontakt med AMK eller legevaktsentral
Øyeblikkelig hjelp hos fastlege
 
***COC/coordination of care***
Skal benyttes når forespørsel om tilgang til helsedata ikke skjer i  direkte forbindelse med den kliniske utførelsen av helsehjelp.  Tilgangsbeslutning hos konsument følger standard regler for tilgangsstyring. 

Eksempler:
Saksbehandling ved tildeling av kommunale helsetjenester


BTG/Break the glass
Skal benyttes når forespørsel om tilgang til helsedata skjer i direkte forbindelse med ytelse av helsehjelp og en overstyring av normale tilgangsregler er nødvendig for umiddelbar tilgang. Tilgangsbeslutning hos konsument følger ikke standard regler for tilgangsstyring. 

Eksempler:

**Comment by eirikbroen** [comment]
Laget et enkelt utkast til tekst

**Comment by steinarnoem** [comment]
Jeg synes dette ser veldig bra ut - legger det inn i dokumentet.

**Comment by steinarnoem** [comment]
Commit: https://github.com/NorskHelsenett/Tillitsrammeverk/commit/7172c87e7b5744fe88a1fc51acb8440d0d33a6e8
