### ISSUE TITLE
Tilhørighet til behandlingssted og detaljert organisasjonstilhørighet for pasienten

### ISSUE THREAD

**Issue by SimVan** [NorskHelsenett/Tillitsrammeverk#92]
Hvilke informasjonselementer beskriver pasientens organisasjonstilhørighet: Legal entity, point-of-care, department ... eller bare point-of-care og department. -- fordi spesifikasjon er inconsistent. I tillegg hvorfor?

**Comment by steinarnoem** [comment]
Fjernet "legal_entity" for pasient fra spesifikasjonen
