### ISSUE TITLE
Informasjon som er ønsket i SAML token men ikke er en del av helsepersonellets attest

### ISSUE THREAD

**Issue by SimVan** [NorskHelsenett/Tillitsrammeverk#93]
Dere har nevnte 2 informasjonselementer som ikke er en del av attest fordi informasjon ikke er inkludert i grunnlaget for hvorfor helsepersonellet fikk tilgang til pasientens informasjon i sitt lokal EPJ:
1 - Helsepersonellets level of assurance som kommer via helsepersonellets brukerpålogging ved bruk av HelseID (ikke EPJ), og
2 - Teknisk tracing referanse som blir generert av EPJ men ikke en del av attest.

Vi må avklare hvilke spesifikasjon skal sikre disse info-elementer kommer frem til SAML-token.

**Comment by steinarnoem** [comment]
Beslutning tatt i andre tråder.. Lukker Issue
