### ISSUE TITLE
Forbedring av eksempler for department i detaljeringen av informasjonsmodellen

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#95]
Eksempelet i informasjonsmodellen inneholder verdier som "resh:xxxxxx" i value-feltet og "resh:x.x.x.x.x" i system-feltet, mens det her er unødvendig og forvirrende å ha med prefixet "resh:" ettersom det skal være lov med andre typer enn bare RESH (og RESH har en egen OID som skal brukes i system, så der er det direkte feil med resh: som prefix). @steinarnoem: Kan du oppdatere eksempelet?

**Comment by steinarnoem** [comment]
Commit: https://github.com/NorskHelsenett/Tillitsrammeverk/commit/d0e424e9cfe5cb98b8df99a1538a832353f1fdd9
