### ISSUE TITLE
Kan decision_ref inneholde user_reason som et fritekstfelt

### ISSUE THREAD

**Issue by richardhus** [NorskHelsenett/Tillitsrammeverk#98]
@RagnhildVa: Vi må få avklart om fritekstfeltet som er foreslått for user_reason under decision_ref er mulig og greit å ha med i informsajonsmodellen (skrevet av Richard på vegne av Simone og featureteamet). Foreslått begrensning av tegn (se forslaget fra Steinar i informasjonsmodellen) og maksimal lengde på type 250/500 tegn eller liknende gjør det forhåpentligvis trygt nok informasjonssikkerhetsmessig...

**Comment by steinarnoem** [comment]
Feltet blir stående i informasjonsmodell for attest til det eventuelt blir tatt ut.
Hvem har ansvar for å vurdere dette? Beslutning påvirker alle (konsument, NHN og dokumentkilde), men dersom HelseID, Kjernejournal eller Dokumentdeling ikke er villig til å transportere/behandle spiller det ikke så stor rolle hva de andre aktørene synes. Kanskje det er lurt om NHN gjør en risikovurdering av dette først? En manglende vilje til å behandle dette i NHN vil jo uansett føre til at attributtet må tas ut..

**Comment by steinarnoem** [comment]
Konklusjon:
Attributtet tas ut av informasjonsmodell og vil ikke støttes i NHN sine løsninger.
