### ISSUE TITLE
Angående validering av attributtet 'healthcare_service' under 'care_relationship'

### ISSUE THREAD

**Issue by runegri** [NorskHelsenett/Tillitsrammeverk#99]
Vi må støtte både 8655, 8627 og 8451. 
Utgåtte kodeverk kan støttes, men vi ønsker ikke at de brukes. Hvordan kommuniserer vi dette?

### Discussed in https://github.com/NorskHelsenett/Tillitsrammeverk/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **oyvind-bech** October  8, 2023</sup>
https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md#427-care_relation-behandlerrelasjon

Kodeverket «Tjenestetyper innen spesialisthelsetjenesten» er markert i dokumentet med Volven-OID 8655 (https://volven.no/produkt.asp?id=507419&catID=3&subID=8), som er beskrevet som «Helsehjelpsområde (OID=8655)».

Derimot har «Tjenestetyper innen spesialisthelsetjenesten» Volven-OID 8627. 

a) hva er korrekt?
b) det hadde vært fint hvis listen med kodeverk hadde vist OID-verdiene i klartekst</div>

**Comment by steinarnoem** [comment]
Slik jeg tolker @richardhus vil vi måtte forholde oss til flere gyldige kodeverk. Jeg har nå oppdatert listen etter beste evne og rullet ut ny versjon av spesifikasjonen.

Commit: https://github.com/NorskHelsenett/Tillitsrammeverk/commit/5105f3956e468b3e14c217d3512276c33062611c
